// Bundles the format CLIs into standalone scripts shipped with the skill,
// and copies the format specification into the skill references.
import { copyFileSync } from 'node:fs';
import { build } from 'esbuild';

const outdir = 'skill/quiz-generator/scripts';
await build({
  entryPoints: { validate: 'format/cli/validate.ts', package: 'format/cli/package.ts' },
  outdir,
  outExtension: { '.js': '.mjs' },
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node18',
  legalComments: 'none',
  minify: true,
  banner: {
    js: '// Generated by scripts/build-skill.mjs from format/cli — do not edit.\nimport { createRequire } from "node:module"; const require = createRequire(import.meta.url);',
  },
});
copyFileSync('docs/format.md', 'skill/quiz-generator/references/format.md');
console.log(`Built ${outdir}/validate.mjs and ${outdir}/package.mjs`);
